# Generated by Django 5.2.5 on 2026-08-23 16:00

import apps.venues.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screen_number', models.PositiveSmallIntegerField()),
                ('total_rows', models.PositiveSmallIntegerField(default=10)),
                ('total_columns', models.PositiveSmallIntegerField(default=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='venues.venue')),
            ],
            options={
                'ordering': ['screen_number'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=4)),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('seat_code', models.CharField(max_length=12)),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('RECLINER', 'Recliner')], default='STANDARD', max_length=16)),
                ('qr_token', models.CharField(default=apps.venues.models.seat_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=16)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.screen')),
            ],
            options={
                'ordering': ['row_label', 'seat_number'],
                'constraints': [models.UniqueConstraint(fields=('screen', 'seat_code'), name='unique_screen_seat')],
            },
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('venue', 'screen_number'), name='unique_venue_screen'),
        ),
    ]
