# Generated by Django 5.2.5 on 2026-08-24 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='screen',
            name='unique_venue_screen',
        ),
        migrations.AddField(
            model_name='screen',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_screens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='screen',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('venue', 'screen_number'), name='unique_active_venue_screen'),
        ),
    ]
